
services:

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017

  web:
    build: .
    restart: always
    command: "python3 manage.py runserver 0.0.0.0:8000 && python3 manage.py makemigrations && python3 manage.py migrate"
    ports:
      - 8000:8000   
    depends_on:
      - mongo

    





  


