# Generated by Django 4.1.9 on 2023-06-12 06:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('ratings', models.IntegerField(default=0)),
                ('images', models.JSONField()),
                ('category', models.IntegerField(choices=[(1, 'Electronics'), (2, 'Clothes'), (3, 'Food')], default=1)),
                ('stock', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(1000)])),
                ('num_of_reviews', models.IntegerField(default=0)),
                ('reviews', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
